{% set name = "gluonts" %}
{% set version = "0.13.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c6a2c963a9e1eeedeb148c24599eddd3fbc79a32e2ec43f9b2df422b125c9c4

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.16,<2
    - pandas >=1.0,<3
    - pydantic >=1.7,<2
    - tqdm >=4.23,<5
    - toolz >=0.10,<1
    - typing-extensions >=4.0,<5  # [py<38]
    # optional deps
    - pytorch
    - pytorch-lightning >=1.5,<3
    - protobuf
    - scipy >=1.10,<1.11

test:
  imports:
    - gluonts
  source_files:
    - test
  requires:
    - pip
    - pytest
    - pyarrow  # [not s390x]
    - statsmodels
    - flaky
    - matplotlib-base
  commands:
    - pip check
    # Skip `test_dataclass_subtype` because of pydantic version incompatibility https://github.com/awslabs/gluonts/issues/1531
    # Skip tests (test_estimators.py, test_modules.py, test_mqf2_modules.py) that require cpflows
    - pytest . -v -k "not test_dataclass_subtype" --ignore=test/torch/model/test_estimators.py --ignore=test/torch/model/test_modules.py --ignore=test/torch/model/test_mqf2_modules.py

about:
  home: https://ts.gluon.ai/stable/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - NOTICE
    - LICENSE
  dev_url: https://github.com/awslabs/gluonts
  doc_url: https://ts.gluon.ai/stable/index.html
  summary: GluonTS is a Python toolkit for probabilistic time series modeling, built around Apache MXNet (incubating).
  description: GluonTS is a Python package for probabilistic time series modeling, focusing on deep learning based models, based on PyTorch and MXNet.

extra:
  recipe-maintainers:
    - dkomisar
